services:
  frontend:
    build:
      context: elevator-ui
      dockerfile: Dockerfile
    expose:
      - 5173
    ports:
      - "3000:5173"
    depends_on:
      - backend
    volumes:
      - ./elevator-ui:/app
      - /app/node_modules

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    expose:
      - 8080
    volumes:
      - .:/app
